### ISSUE TITLE
how to make dtb file?

### ISSUE THREAD

**Issue by jamesarch** [corellium/preloader-m1#1]
my laptop is MacBook Air (M1, 2020) Code name is `j313` ,and i have use `linux.macho` to boot linux image have issue stock message 
`Loader complete, relocating kernel...`

so i think maybe wrong model? so i try build latest `linux.macho`  but i can't make like this [apple-m1-j274.dts](https://github.com/corellium/linux-m1/blob/master/arch/arm64/boot/dts/apple/apple-m1-j274.dts)

now i have found `DeviceTree.j313ap.im4p` in 
`/System/Volumes/Preboot/6E86E53B-47E3-4E34-A38D-E78C4BC62F6D/restore/Firmware/all_flash`
how to convert to dts? 

Thank you for your hard work

**Comment by leeehui** [comment]
@jamesarch   
dtb is automatically built when you make kernel
https://github.com/corellium/linux-m1.git

**Comment by leeehui** [comment]
it seems currently Air is not supported ？

**Comment by leeehui** [comment]
@jamesarch 
maybe try this
https://github.com/Shizmob/img4.git

**Comment by jamesarch** [comment]
> @jamesarch
> maybe try this
> https://github.com/Shizmob/img4.git
😂 ok i just watch[ this video ](https://www.youtube.com/watch?v=d5s9fYfvzmY&feature=youtu.be)found this tools thanks

PS:how to compile[ linux-m1](https://github.com/corellium/linux-m1) kernel? just run make??

**Comment by leeehui** [comment]
I haven't tried it yet,  try the following cmds:
ARCH=arm64
CROSS_COMPILE=your cross compiler path/aarch64-linux-gnu-
make defconfig    
make menuconfig --> find platform configuration and enable Apple platform
make -j your core numbers

**Comment by jamesarch** [comment]
> I haven't tried it yet, try the following cmds:
> ARCH=arm64
> CROSS_COMPILE=your cross compiler path/aarch64-linux-gnu-
> make defconfig
> make menuconfig --> find platform configuration and enable Apple platform
> make -j your core numbers

ok thanks

**Comment by leeehui** [comment]
@jamesarch 
How you boot linux.macho?
more specifically, where did you execute the following command?  1TR or MacOS ? I got parameter error on MacOS
kmutil configure-boot -c test.macho -v /Volumes/Macintosh HD/
